name       : eog
version    : '41.0'
release    : 46
source     :
    - https://download.gnome.org/sources/eog/41/eog-41.0.tar.xz : 917de086fd97fd3ec930fa07c88badd2be1f5d0ae6b9e569c986004e0359a9ac
license    : GPL-2.0-only
component  : multimedia.graphics
summary    : The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections.
description: |
    The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections. The Eye of GNOME supports a variety of image file formats. The GdkPixbuf library determines which file formats Eye of GNOME can load and save.
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(shared-mime-info)
    - libjpeg-turbo-devel
    - itstool
setup      : |
    %meson_configure -Dlibportal=false
build      : |
    %ninja_build
install    : |
    %ninja_install
