name       : eog
version    : 3.20.4
release    : 20
source     :
    - http://ftp.gnome.org/pub/gnome/sources/eog/3.20/eog-3.20.4.tar.xz : 968774cc07ea0d3c27ac552dc0f1d51cf682b9036d342b447688a208f31a5be3
license    : GPL-2.0
component  : multimedia.graphics
summary    : The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections.
description: |
    The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections. The Eye of GNOME supports a variety of image file formats. The GdkPixbuf library determines which file formats Eye of GNOME can load and save.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - libjpeg-turbo-devel
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
