name        : eog
version     : 3.18.2
release     : 16
source     :
    - http://ftp.gnome.org/pub/gnome/sources/eog/3.18/eog-3.18.2.tar.xz : dc2d16e3754cad12703261fe586e7599c4df2e39282f6c28681a514f749fe636
license     : GPL-2.0+
summary     : The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - libjpeg-turbo-devel
    - itstool
description : |
    The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections. The Eye of GNOME supports a variety of image file formats. The GdkPixbuf library determines which file formats Eye of GNOME can load and save.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
