name       : eog
version    : 3.34.1
release    : 33
source     :
    - https://download.gnome.org/sources/eog/3.34/eog-3.34.1.tar.xz : fdb0739f8420af2ffb8e91c766a154afefdf20f721ad34b56cab27fd1569f42c
license    : GPL-2.0-only
component  : multimedia.graphics
summary    : The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections.
description: |
    The Eye of GNOME image viewer is the official image viewer for the GNOME Desktop environment. With it, you can view single image files, as well as large image collections. The Eye of GNOME supports a variety of image file formats. The GdkPixbuf library determines which file formats Eye of GNOME can load and save.
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(shared-mime-info)
    - libjpeg-turbo-devel
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
